/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;

/**
 *
 * @author wanderson
 */
public class JFAjuda extends javax.swing.JFrame {

    /**
     * Creates new form JFAjuda
     */
    public JFAjuda() {
        initComponents();
        ajuda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spEditor = new javax.swing.JScrollPane();
        epAjuda = new javax.swing.JEditorPane();
        spMenu = new javax.swing.JScrollPane();
        jlMenu = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajuda");

        epAjuda.setEditable(false);
        spEditor.setViewportView(epAjuda);

        jlMenu.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Inicial", "Tela Principal", "Clientes", "Técnicos", "Ocorrências", "Casos" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jlMenu.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlMenu.setSelectedIndex(0);
        jlMenu.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlMenuValueChanged(evt);
            }
        });
        spMenu.setViewportView(jlMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spEditor)
                    .addComponent(spMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlMenuValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlMenuValueChanged
        // TODO add your handling code here:
        ajuda();
    }//GEN-LAST:event_jlMenuValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane epAjuda;
    private javax.swing.JList jlMenu;
    private javax.swing.JScrollPane spEditor;
    private javax.swing.JScrollPane spMenu;
    // End of variables declaration//GEN-END:variables

    private void ajuda() {

        HTMLEditorKit kit = new HTMLEditorKit();
        epAjuda.setEditorKit(kit);
        String htmlString = "";
        
        if (jlMenu.getSelectedIndex() == 0) {
            htmlString = new String("<html> <head> <title></title> </head> <body> <p style=\"text-align: center;\"> <b><u>RBC-MI</u></b></p> <p style=\"text-align: justify;\"> Esta &eacute; a janela de ajuda do sistema RBC-MI, onde se encontram uma vers&atilde;o resumida das informa&ccedil;&otilde;es sobre as funcionalidades e caracter&iacute;sticas do programa.</p> <p style=\"text-align: justify;\"> &Eacute; importante frisar que, em qualquer etapa e janela de execu&ccedil;&atilde;o do sistema &eacute; poss&iacute;vel acessar dicas de utiliza&ccedil;&atilde;o movimentando o cursor do mouse sobre o item que se deseja obter ajuda.</p> <p style=\"text-align: justify;\"> Este sistema foi desenvolvido por Wanderson Werner B&uuml;ttelbrun, como parte do Trabalho de Conclus&atilde;o de Curso, sob orienta&ccedil;&atilde;o do professor Ant&ocirc;nio Carlos Tamanini, na Universidade do Estado de Santa Catarina.</p> </body> </html>");
        } else {
            if (jlMenu.getSelectedIndex() == 1) {
                htmlString = new String("<html> <head> <title></title> </head> <body> <p style=\"text-align: center;\"> <strong><u>Tela Principal</u></strong></p> <p style=\"text-align: justify;\"> A janela principal &eacute; o local onde temos o acesso a todoas as funcionalidades do sistema;</p> <p style=\"text-align: justify;\"> O menu principal cont&eacute;m todos os itens e janelas acess&iacute;veis: <em><strong>Arquivo, Cadastro, Consulta e Ajuda;</strong></em></p> <p style=\"text-align: justify;\"> O item de menu <strong><em>Arquivo</em></strong> possui um subitem <strong><em>Sair</em></strong>, por onde &eacute; poss&iacute;vel finalizar a execu&ccedil;&atilde;o do sistema;</p> <p style=\"text-align: justify;\"> O item de menu <em><strong>Cadastro</strong></em> &eacute; o local onde encontram-se todas as telas de cadastro de informa&ccedil;&otilde;es do sistema, que s&atilde;o: <em><strong>Clientes, T&eacute;cnicos, Ocorr&ecirc;ncias e Casos;</strong></em></p> <p style=\"text-align: justify;\"> O item de menu <em><strong>Consulta</strong></em> &eacute; o item que d&aacute; acesso a todas as informa&ccedil;&otilde;es armazenadas no sistema atrav&eacute;s das telas de cadastros, al&eacute;m de possibilitar a edi&ccedil;&atilde;o das mesmas;</p> <p style=\"text-align: justify;\"> O item de menu <em><strong>Ajuda</strong></em> &eacute; o local que cont&eacute;m uma breve documenta&ccedil;&atilde;o do sistema com o objetivo de auxilar o usu&aacute;rio na opera&ccedil;&atilde;o do sistema;</p> <p style=\"text-align: justify;\"> Ainda na tela principal do sistema est&aacute; localizada uma tabela que d&aacute; acesso r&aacute;pido a todas ocorr&ecirc;ncias em aberto, facilitando a vizualiza&ccedil;&atilde;o do usu&aacute;rio.</p> </body> </html>");
            } else {
                if (jlMenu.getSelectedIndex() == 2) {
                    htmlString = new String("<html> <head> <title></title> </head> <body> <p style=\"text-align: center;\"> <b><u>Clientes</u></b></p> <p style=\"text-align: justify;\"> Os clientes s&atilde;o pessoas f&iacute;sicas ou jur&iacute;dicas;</p> <p style=\"text-align: justify;\"> As opera&ccedil;&otilde;es com os clientes s&atilde;o: <em><strong>Cadastro e Consulta;</strong></em></p> <p style=\"text-align: justify;\"> Para cadastrar um cliente: <em><strong>Menu &gt; Cadastro &gt; Clientes;</strong></em></p> <p style=\"text-align: justify;\"> Para consultar ou alterar um cliente: <em><strong>Menu &gt; Consulta &gt; Clientes;</strong></em></p> </body> </html>");
                } else {
                    if (jlMenu.getSelectedIndex() == 3) {
                        htmlString = new String("<html> <head> <title></title> </head> <body> <p style=\"text-align: center;\"> <b><u>T&eacute;cnicos</u></b></p> <p style=\"text-align: justify;\"> Os t&eacute;cnicos s&atilde;o pessoas f&iacute;sicas que fazem a manuten&ccedil;&atilde;o nos computadores;</p> <p style=\"text-align: justify;\"> As opera&ccedil;&otilde;es com os t&eacute;cnicos s&atilde;o: <em><strong>Cadastro e Consulta;</strong></em></p> <p style=\"text-align: justify;\"> Para cadastrar um t&eacute;cnico: <em><strong>Menu &gt; Cadastro &gt; T&eacute;cnicos;</strong></em></p> <p style=\"text-align: justify;\"> Para consultar ou alterar um t&eacute;cnico: <em><strong>Menu &gt; Consulta &gt; T&eacute;cnicos;</strong></em></p> </body> </html>");
                    } else {
                        if (jlMenu.getSelectedIndex() == 4) {
                            htmlString = new String("<html> <head> <title></title> </head> <body> <p style=\"text-align: center;\"> <b><u>Ocorr&ecirc;ncias</u></b></p> <p style=\"text-align: justify;\"> As ocorr&ecirc;ncias s&atilde;o uma parte fundamental do sistema. Sempre quando um equipamento chega para o conserto, &eacute; necess&aacute;rio abrir uma ocorr&ecirc;ncia, informando o problema, o cliente e outros dados relevantes;</p> <p style=\"text-align: justify;\"> Para cadastrar uma ocorr&ecirc;ncia: <em><strong>Menu &gt; Cadastro &gt; Ocorr&ecirc;ncias;</strong></em></p> <p style=\"text-align: justify;\"> Para consultar ou alterar uma ocorr&ecirc;ncia: <em><strong>Menu &gt; Consulta &gt; Ocorr&ecirc;ncias,&nbsp;</strong></em>ou se ela estiver aberta ela pode ser localizada na tabela de ocorr&ecirc;ncias em aberto na tela principal do sistema;</p> </body> </html>");
                        } else {
                            htmlString = new String("<html> <head> <title></title> </head> <body> <p style=\"text-align: center;\"> <b><u>Casos</u></b></p> <p style=\"text-align: justify;\"> O Racioc&iacute;nio Baseado em Casos &eacute; uma t&eacute;cnica que utiliza de casos para recuperar e armazenar conhecimento oriundos de experi&ecirc;ncias. O caso cont&eacute;m os atributos que o identificam e informa&ccedil;&otilde;es que possibilitam o sistema aprender e adaptar uma solu&ccedil;&atilde;o para um novo problema.</p> <p style=\"text-align: justify;\"> Para cadastrar um caso separadamente: <em><strong>Menu &gt; Cadastro &gt; Caso;</strong></em></p> <p style=\"text-align: justify;\"> Outra op&ccedil;&atilde;o interessante &eacute; cadastrar um caso junto a ocorr&ecirc;ncia (visto que isso &eacute; necess&aacute;rio), para isto, abra uma ocorr&ecirc;ncia e clique no bot&atilde;o <strong>Adicionar Caso</strong> na janela de atualiza&ccedil;&atilde;o de Ocorr&ecirc;ncias;</p> <p style=\"text-align: justify;\"> Os casos podem ser cadastrados de duas formas, por <strong><em>Categoria de Poblema</em></strong> (recomend&aacute;vel) ou por <strong><em>Sele&ccedil;&atilde;o Livre de Atributos </em></strong>(quando os atributos n&atilde;o se encaixam em somente uma categoria);</p> <p style=\"text-align: justify;\"> Depois de preencher todos os campos, o clico RBC &eacute; iniciado, durante o processo, para qualquer d&uacute;vida, &eacute; recomed&aacute;vel movimentar o mouse sobre os campos para obter ajuda;</p> <p style=\"text-align: justify;\"> Para consultar um caso: <em><strong>Menu &gt; Consulta &gt; Casos.</strong></em></p> </body> </html>");
                        }
                    }
                }
            }
        }
            
        Document doc = kit.createDefaultDocument();
        epAjuda.setDocument(doc);
        epAjuda.setText(htmlString);
        
    }
               
}
