/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Beans.Cliente;
import Beans.Ocorrencia;
import DAO.DAOCliente;
import DAO.DAOOcorrencia;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Wanderson
 */
public class JFCadOcorrencia extends javax.swing.JFrame {

    /**
     * Creates new form JFCadOcorrencia
     */
    public JFCadOcorrencia() {
        initComponents();
        cbPrioridade.setSelectedIndex(1);
        dataAtual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpOcorrencia = new javax.swing.JPanel();
        lbCliente = new javax.swing.JLabel();
        btBuscar = new javax.swing.JButton();
        tfCliente = new javax.swing.JTextField();
        lbProblema = new javax.swing.JLabel();
        spProblema = new javax.swing.JScrollPane();
        taProblema = new javax.swing.JTextArea();
        lbPrioridade = new javax.swing.JLabel();
        cbPrioridade = new javax.swing.JComboBox();
        lbDataAbertura = new javax.swing.JLabel();
        ftfDataAbertura = new javax.swing.JFormattedTextField();
        btNovo = new javax.swing.JButton();
        lbEquipamento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taEquipamento = new javax.swing.JTextArea();
        btCadastrar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Ocorrência");

        jpOcorrencia.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbCliente.setText("Código Cliente");

        btBuscar.setText("Buscar");
        btBuscar.setToolTipText("Buscar cliente através de listagem.");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        tfCliente.setToolTipText("Código do Cliente, somente números.");

        lbProblema.setText("Problema Relatado");

        taProblema.setColumns(20);
        taProblema.setLineWrap(true);
        taProblema.setRows(5);
        taProblema.setToolTipText("Descrição sucinta do problema informado pelo cliente.");
        taProblema.setWrapStyleWord(true);
        spProblema.setViewportView(taProblema);

        lbPrioridade.setText("Prioridade");

        cbPrioridade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Baixa", "Normal", "Alta" }));
        cbPrioridade.setToolTipText("Escolha a prioridade de atendimento da ocorrência. Ocorrências com prioridade alta são listadas primeiro.");

        lbDataAbertura.setText("Data Abertura");

        try {
            ftfDataAbertura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfDataAbertura.setToolTipText("Data de abertura da ocorrência no fomato DD/MM/AAAA.");

        btNovo.setText("Novo");
        btNovo.setToolTipText("Cadastrar novo cliente.");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        lbEquipamento.setText("Descrição do equipamento defeituoso");

        taEquipamento.setColumns(20);
        taEquipamento.setRows(5);
        taEquipamento.setToolTipText("Descrição do equipamento do cliente, utilize informações como marca, modelo, tipo de hardware e outros dados relevantes.");
        taEquipamento.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taEquipamento);

        javax.swing.GroupLayout jpOcorrenciaLayout = new javax.swing.GroupLayout(jpOcorrencia);
        jpOcorrencia.setLayout(jpOcorrenciaLayout);
        jpOcorrenciaLayout.setHorizontalGroup(
            jpOcorrenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOcorrenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpOcorrenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spProblema)
                    .addComponent(jScrollPane1)
                    .addGroup(jpOcorrenciaLayout.createSequentialGroup()
                        .addGroup(jpOcorrenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbProblema)
                            .addGroup(jpOcorrenciaLayout.createSequentialGroup()
                                .addGroup(jpOcorrenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDataAbertura)
                                    .addComponent(lbPrioridade))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpOcorrenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbPrioridade, 0, 89, Short.MAX_VALUE)
                                    .addComponent(ftfDataAbertura)))
                            .addComponent(lbEquipamento))
                        .addGap(0, 179, Short.MAX_VALUE))
                    .addGroup(jpOcorrenciaLayout.createSequentialGroup()
                        .addComponent(lbCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpOcorrenciaLayout.setVerticalGroup(
            jpOcorrenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOcorrenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpOcorrenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCliente)
                    .addComponent(btBuscar)
                    .addComponent(tfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNovo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbProblema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spProblema, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbEquipamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpOcorrenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrioridade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpOcorrenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDataAbertura)
                    .addComponent(ftfDataAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btCadastrar.setText("Cadastrar");
        btCadastrar.setToolTipText("Armazena as informações no sistema.");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.setToolTipText("Fecha janela atual.");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpOcorrencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpOcorrencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btCadastrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        JFListaCliente listaCliente = new JFListaCliente(this);
        listaCliente.setLocationRelativeTo(this);
        listaCliente.setVisible(true);
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
        armazenar();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        JFCadCliente cadCliente = new JFCadCliente(this);
        cadCliente.setLocationRelativeTo(this);
        cadCliente.setVisible(true);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btNovo;
    private javax.swing.JComboBox cbPrioridade;
    private javax.swing.JFormattedTextField ftfDataAbertura;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpOcorrencia;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbDataAbertura;
    private javax.swing.JLabel lbEquipamento;
    private javax.swing.JLabel lbPrioridade;
    private javax.swing.JLabel lbProblema;
    private javax.swing.JScrollPane spProblema;
    private javax.swing.JTextArea taEquipamento;
    private javax.swing.JTextArea taProblema;
    private javax.swing.JTextField tfCliente;
    // End of variables declaration//GEN-END:variables

    public void armazenar() {
        
        Date data;
        
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        
        try {
            data = new java.sql.Date(df.parse(ftfDataAbertura.getText()).getTime());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Data informada é inválida, detalhes:\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        DAOCliente dAOCliente = new DAOCliente();
        Cliente cliente;
        
        try {
            cliente = dAOCliente.listarId(Integer.parseInt(tfCliente.getText()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Código do cliente nulo ou inválido, detalhes:\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (cliente == null) {
            JOptionPane.showMessageDialog(null, "Código do cliente não existe, verifique-o ou adicione um novo cliente.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
             
        Ocorrencia ocorrencia = new Ocorrencia();
        
        ocorrencia.setCliente(cliente);
        ocorrencia.setDtAbertura(data);
        ocorrencia.setEstOcorrencia(0);
        ocorrencia.setPriOcorrencia(cbPrioridade.getSelectedIndex());
        ocorrencia.setProbOcorrencia(taProblema.getText());
        ocorrencia.setDesEquipamento(taEquipamento.getText());
        
        DAOOcorrencia daoOcorrencia = new DAOOcorrencia();
       
        try {
            daoOcorrencia.armazenar(ocorrencia);
            JOptionPane.showMessageDialog(null, "Ocorrência armazenada!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception ex) {
             JOptionPane.showMessageDialog(null, "Houve algum problema com o cadastro da ocorrência, detalhes:\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }
              
    }
    
    private void dataAtual() {
        
        Date hoje = new Date();
        SimpleDateFormat df;
        df = new SimpleDateFormat("dd/MM/yyyy");
        ftfDataAbertura.setText("" + df.format(hoje));
        
    }
    
    public void insereIdCliente(int id){
        
        tfCliente.setText(""+id);
        
    }
    
}
