/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Beans.Caso;

/**
 *
 * @author wanderson
 */
public class JFDetalhesCaso extends javax.swing.JFrame {

    /**
     * Creates new form JFDetalhesCaso
     */
    public JFDetalhesCaso(Caso c) {
        initComponents();
        caso = c;
        setCaso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spAtributos = new javax.swing.JScrollPane();
        jpAtributos = new javax.swing.JPanel();
        jpSom = new javax.swing.JPanel();
        lbEstsom = new javax.swing.JLabel();
        lbEstpersom = new javax.swing.JLabel();
        lbQtdsom = new javax.swing.JLabel();
        lbSitsom = new javax.swing.JLabel();
        lbQtdsomV = new javax.swing.JLabel();
        lbEstpersomV = new javax.swing.JLabel();
        lbEstdrsomV = new javax.swing.JLabel();
        lbSitsomV = new javax.swing.JLabel();
        jpRede = new javax.swing.JPanel();
        lbEnddns = new javax.swing.JLabel();
        lbEndip = new javax.swing.JLabel();
        lbEstredeso = new javax.swing.JLabel();
        lbRj45 = new javax.swing.JLabel();
        lbInfra = new javax.swing.JLabel();
        lbConinternet = new javax.swing.JLabel();
        lbConrede = new javax.swing.JLabel();
        lbEstredesoV = new javax.swing.JLabel();
        lbEndipV = new javax.swing.JLabel();
        lbEnddnsV = new javax.swing.JLabel();
        lbRj45V = new javax.swing.JLabel();
        lbEstdriverredeV = new javax.swing.JLabel();
        lbEstdriverrede = new javax.swing.JLabel();
        lbInfraV = new javax.swing.JLabel();
        lbConinternetV = new javax.swing.JLabel();
        lbConredeV = new javax.swing.JLabel();
        jpImpressao = new javax.swing.JPanel();
        lbEstimpso = new javax.swing.JLabel();
        lbEstdriverimp = new javax.swing.JLabel();
        lbLedimp = new javax.swing.JLabel();
        lbEstgeralimp = new javax.swing.JLabel();
        lbNivelcar = new javax.swing.JLabel();
        lbFilaimp = new javax.swing.JLabel();
        lbConimp = new javax.swing.JLabel();
        lbTipoimp = new javax.swing.JLabel();
        lbFilaimpV = new javax.swing.JLabel();
        lbNivelcarV = new javax.swing.JLabel();
        lbEstgeralimpV = new javax.swing.JLabel();
        lbLedimpV = new javax.swing.JLabel();
        lbEstdriverimpV = new javax.swing.JLabel();
        lbTipoimsoV = new javax.swing.JLabel();
        lbConimpV = new javax.swing.JLabel();
        lbEstimpsoV = new javax.swing.JLabel();
        jpDiversos = new javax.swing.JPanel();
        lbMsgerro = new javax.swing.JLabel();
        lbHwnovo = new javax.swing.JLabel();
        lbSujgab = new javax.swing.JLabel();
        lbCabint = new javax.swing.JLabel();
        lbHwnovoV = new javax.swing.JLabel();
        lbSujgabV = new javax.swing.JLabel();
        lbCabintV = new javax.swing.JLabel();
        lbMsgerroV = new javax.swing.JLabel();
        lbLedgab = new javax.swing.JLabel();
        lbLedgabV = new javax.swing.JLabel();
        jpTrava = new javax.swing.JPanel();
        lbArqso = new javax.swing.JLabel();
        lbEsphd = new javax.swing.JLabel();
        lbLedhd = new javax.swing.JLabel();
        lbEstso = new javax.swing.JLabel();
        lbEstav = new javax.swing.JLabel();
        lbQtdram = new javax.swing.JLabel();
        lbQtdcore = new javax.swing.JLabel();
        lbSoins = new javax.swing.JLabel();
        lbSitpcre = new javax.swing.JLabel();
        lbTempcpu = new javax.swing.JLabel();
        lbVelcpu = new javax.swing.JLabel();
        lbSitpcreV = new javax.swing.JLabel();
        lbSoinsV = new javax.swing.JLabel();
        lbTempcpuV = new javax.swing.JLabel();
        lbVelcpuV = new javax.swing.JLabel();
        lbQtdcoreV = new javax.swing.JLabel();
        lbQtdramV = new javax.swing.JLabel();
        lbEstavV = new javax.swing.JLabel();
        lbEstsoV = new javax.swing.JLabel();
        lbLedhdV = new javax.swing.JLabel();
        lbEsphdV = new javax.swing.JLabel();
        lbArqsoV = new javax.swing.JLabel();
        jpInicializacao = new javax.swing.JPanel();
        lbBeeps = new javax.swing.JLabel();
        lbDatabios = new javax.swing.JLabel();
        lbHdbios = new javax.swing.JLabel();
        lbDatabiosV = new javax.swing.JLabel();
        lbHdbiosV = new javax.swing.JLabel();
        lbBeepsV = new javax.swing.JLabel();
        jpNaoliga = new javax.swing.JPanel();
        lbBtpower = new javax.swing.JLabel();
        lbCabenergia = new javax.swing.JLabel();
        lbEquipp = new javax.swing.JLabel();
        lbVoltpsu = new javax.swing.JLabel();
        lbCabenergiaV = new javax.swing.JLabel();
        lbEquippV = new javax.swing.JLabel();
        lbBtpowerV = new javax.swing.JLabel();
        lbVoltpsuV = new javax.swing.JLabel();
        jpVideo = new javax.swing.JPanel();
        lbTela = new javax.swing.JLabel();
        lbEstdrivervideo = new javax.swing.JLabel();
        lbEstmonitor = new javax.swing.JLabel();
        lbTempvga = new javax.swing.JLabel();
        lbTipovga = new javax.swing.JLabel();
        lbTelaV = new javax.swing.JLabel();
        lbEstdrivervideoV = new javax.swing.JLabel();
        lbEstmonitorV = new javax.swing.JLabel();
        lbTemvgaV = new javax.swing.JLabel();
        lbTipovgaV = new javax.swing.JLabel();
        jpConclusao = new javax.swing.JPanel();
        lbDiagnostico = new javax.swing.JLabel();
        lbCorretiva = new javax.swing.JLabel();
        spSolucao = new javax.swing.JScrollPane();
        taSolucao = new javax.swing.JTextArea();
        spResultado = new javax.swing.JScrollPane();
        taResultado = new javax.swing.JTextArea();
        btFechar = new javax.swing.JButton();
        lbCodCaso = new javax.swing.JLabel();
        lbCaso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalhes do Caso");

        jpAtributos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jpSom.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Som")));

        lbEstsom.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbEstsom.setText("Estado do Driver de som:");

        lbEstpersom.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbEstpersom.setText("Estado do periférico de som:");

        lbQtdsom.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbQtdsom.setText("Quantidade de dispositivos de áudio:");

        lbSitsom.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbSitsom.setText("Situação que o som não funciona:");

        lbQtdsomV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbQtdsomV.setText("---");

        lbEstpersomV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbEstpersomV.setText("---");

        lbEstdrsomV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbEstdrsomV.setText("---");

        lbSitsomV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbSitsomV.setText("---");

        javax.swing.GroupLayout jpSomLayout = new javax.swing.GroupLayout(jpSom);
        jpSom.setLayout(jpSomLayout);
        jpSomLayout.setHorizontalGroup(
            jpSomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSitsom, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEstsom)
                    .addComponent(lbEstpersom)
                    .addComponent(lbQtdsom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpSomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEstdrsomV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbQtdsomV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbEstpersomV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbSitsomV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpSomLayout.setVerticalGroup(
            jpSomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstsom)
                    .addComponent(lbEstdrsomV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpSomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstpersom)
                    .addComponent(lbEstpersomV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpSomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQtdsom)
                    .addComponent(lbQtdsomV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpSomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSitsom)
                    .addComponent(lbSitsomV))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpRede.setBorder(javax.swing.BorderFactory.createTitledBorder("Rede e Internet"));

        lbEnddns.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbEnddns.setText("Endereço DNS: ");

        lbEndip.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbEndip.setText("Endereço IP: ");

        lbEstredeso.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbEstredeso.setText("Estado da conexão de rede no SO:");

        lbRj45.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbRj45.setText("Estado do conector RJ45: ");

        lbInfra.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbInfra.setText("Infraestrutura de rede:");

        lbConinternet.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbConinternet.setText("Tipo de conexão de Internet:");

        lbConrede.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbConrede.setText("Tipo de conexão de Rede:");

        lbEstredesoV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbEstredesoV.setText("---");

        lbEndipV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbEndipV.setText("---");

        lbEnddnsV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbEnddnsV.setText("---");

        lbRj45V.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbRj45V.setText("---");

        lbEstdriverredeV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbEstdriverredeV.setText("---");

        lbEstdriverrede.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbEstdriverrede.setText("Estado do Driver da placa de rede:");

        lbInfraV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbInfraV.setText("---");

        lbConinternetV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbConinternetV.setText("---");

        lbConredeV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbConredeV.setText("---");

        javax.swing.GroupLayout jpRedeLayout = new javax.swing.GroupLayout(jpRede);
        jpRede.setLayout(jpRedeLayout);
        jpRedeLayout.setHorizontalGroup(
            jpRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRedeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEnddns)
                    .addComponent(lbEndip)
                    .addComponent(lbEstredeso)
                    .addComponent(lbRj45)
                    .addComponent(lbEstdriverrede)
                    .addComponent(lbInfra)
                    .addComponent(lbConinternet)
                    .addComponent(lbConrede))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbConinternetV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbInfraV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbEstdriverredeV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbRj45V, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbEstredesoV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbEndipV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbConredeV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbEnddnsV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpRedeLayout.setVerticalGroup(
            jpRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRedeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEnddns)
                    .addComponent(lbEnddnsV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndip)
                    .addComponent(lbEndipV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstredeso)
                    .addComponent(lbEstredesoV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRj45)
                    .addComponent(lbRj45V))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstdriverredeV)
                    .addComponent(lbEstdriverrede))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbInfra)
                    .addComponent(lbInfraV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConinternet)
                    .addComponent(lbConinternetV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpRedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConrede)
                    .addComponent(lbConredeV))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpImpressao.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Impressão")));

        lbEstimpso.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbEstimpso.setText("Estado da impressora no SO:");

        lbEstdriverimp.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbEstdriverimp.setText("Estado do Driver da impressora: ");

        lbLedimp.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbLedimp.setText("Estado do LED da impressora:");

        lbEstgeralimp.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbEstgeralimp.setText("Estado Geral da impressora:");

        lbNivelcar.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbNivelcar.setText("Nível do cartucho:");

        lbFilaimp.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbFilaimp.setText("Fila de impressão:");

        lbConimp.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbConimp.setText("Tipo de conexão da impressora:");

        lbTipoimp.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbTipoimp.setText("Tipo de impressora no SO:");

        lbFilaimpV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbFilaimpV.setText("---");

        lbNivelcarV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbNivelcarV.setText("---");

        lbEstgeralimpV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbEstgeralimpV.setText("---");

        lbLedimpV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbLedimpV.setText("---");

        lbEstdriverimpV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbEstdriverimpV.setText("---");

        lbTipoimsoV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbTipoimsoV.setText("---");

        lbConimpV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbConimpV.setText("---");

        lbEstimpsoV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbEstimpsoV.setText("---");

        javax.swing.GroupLayout jpImpressaoLayout = new javax.swing.GroupLayout(jpImpressao);
        jpImpressao.setLayout(jpImpressaoLayout);
        jpImpressaoLayout.setHorizontalGroup(
            jpImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpImpressaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpImpressaoLayout.createSequentialGroup()
                        .addGroup(jpImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLedimp)
                            .addComponent(lbEstgeralimp)
                            .addGroup(jpImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbFilaimp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbNivelcar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbConimp)
                            .addComponent(lbTipoimp))
                        .addGap(469, 470, Short.MAX_VALUE))
                    .addGroup(jpImpressaoLayout.createSequentialGroup()
                        .addGroup(jpImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEstimpso)
                            .addComponent(lbEstdriverimp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbEstimpsoV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTipoimsoV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNivelcarV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbEstgeralimpV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbLedimpV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbConimpV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbFilaimpV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbEstdriverimpV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13))))
        );
        jpImpressaoLayout.setVerticalGroup(
            jpImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpImpressaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstimpso)
                    .addComponent(lbEstimpsoV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstdriverimpV)
                    .addComponent(lbEstdriverimp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLedimp)
                    .addComponent(lbLedimpV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstgeralimp)
                    .addComponent(lbEstgeralimpV, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNivelcar)
                    .addComponent(lbNivelcarV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFilaimpV, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbFilaimp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConimp)
                    .addComponent(lbConimpV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpImpressaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipoimp)
                    .addComponent(lbTipoimsoV))
                .addContainerGap())
        );

        jpDiversos.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos usados em várias Categorias"));

        lbMsgerro.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbMsgerro.setText("Mensagem de Erro:");

        lbHwnovo.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbHwnovo.setText("Peça nova recentemente instalada:");

        lbSujgab.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbSujgab.setText("Sujeira dentro do gabinete:");

        lbCabint.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbCabint.setText("Cabeamento interno do gabinete:");

        lbHwnovoV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbHwnovoV.setText("---");

        lbSujgabV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbSujgabV.setText("---");

        lbCabintV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbCabintV.setText("---");

        lbMsgerroV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbMsgerroV.setText("---");

        lbLedgab.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbLedgab.setText("Funcionamento dos LEDs no gabinete:");

        lbLedgabV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbLedgabV.setText("---");

        javax.swing.GroupLayout jpDiversosLayout = new javax.swing.GroupLayout(jpDiversos);
        jpDiversos.setLayout(jpDiversosLayout);
        jpDiversosLayout.setHorizontalGroup(
            jpDiversosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDiversosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDiversosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDiversosLayout.createSequentialGroup()
                        .addGroup(jpDiversosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMsgerro, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbHwnovo)
                            .addComponent(lbSujgab)
                            .addComponent(lbCabint))
                        .addGap(25, 25, 25)
                        .addGroup(jpDiversosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSujgabV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbCabintV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbHwnovoV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbMsgerroV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpDiversosLayout.createSequentialGroup()
                        .addComponent(lbLedgab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLedgabV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpDiversosLayout.setVerticalGroup(
            jpDiversosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDiversosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDiversosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMsgerro)
                    .addComponent(lbMsgerroV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDiversosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHwnovo)
                    .addComponent(lbHwnovoV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDiversosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSujgab)
                    .addComponent(lbSujgabV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDiversosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCabintV)
                    .addComponent(lbCabint))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDiversosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLedgab)
                    .addComponent(lbLedgabV))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpTrava.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Lentidão e Travamentos")));

        lbArqso.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbArqso.setText("Arquitetura do S.O.:");

        lbEsphd.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbEsphd.setText("Espaço livre em disco (GBs):");

        lbLedhd.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbLedhd.setText("Estado do LED do HD:");

        lbEstso.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbEstso.setText("Estado do Sistema Operacional:");

        lbEstav.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbEstav.setText("Estado do software antivírus:");

        lbQtdram.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbQtdram.setText("Quantidade de memória RAM instalada:");

        lbQtdcore.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbQtdcore.setText("Quantidade de núcleos do processador:");

        lbSoins.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbSoins.setText("Sistema Operacional instalado:");

        lbSitpcre.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbSitpcre.setText("Situação em que o pc reinicia inesperadamente:");

        lbTempcpu.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbTempcpu.setText("Temperatura do processador:");

        lbVelcpu.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbVelcpu.setText("Velocidade do processador (GHz):");

        lbSitpcreV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbSitpcreV.setText("---");

        lbSoinsV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbSoinsV.setText("---");

        lbTempcpuV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbTempcpuV.setText("---");

        lbVelcpuV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbVelcpuV.setText("---");

        lbQtdcoreV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbQtdcoreV.setText("---");

        lbQtdramV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbQtdramV.setText("---");

        lbEstavV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbEstavV.setText("---");

        lbEstsoV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbEstsoV.setText("---");

        lbLedhdV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbLedhdV.setText("---");

        lbEsphdV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbEsphdV.setText("---");

        lbArqsoV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbArqsoV.setText("---");

        javax.swing.GroupLayout jpTravaLayout = new javax.swing.GroupLayout(jpTrava);
        jpTrava.setLayout(jpTravaLayout);
        jpTravaLayout.setHorizontalGroup(
            jpTravaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTravaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTravaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSitpcre)
                    .addComponent(lbEsphd)
                    .addComponent(lbLedhd)
                    .addComponent(lbEstso)
                    .addComponent(lbEstav)
                    .addComponent(lbQtdram)
                    .addComponent(lbQtdcore)
                    .addComponent(lbSoins)
                    .addComponent(lbTempcpu)
                    .addComponent(lbVelcpu)
                    .addComponent(lbArqso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTravaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbArqsoV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbSitpcreV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbEsphdV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbLedhdV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbEstsoV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbEstavV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbQtdramV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbQtdcoreV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbSoinsV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTempcpuV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbVelcpuV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpTravaLayout.setVerticalGroup(
            jpTravaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTravaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTravaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbArqso)
                    .addComponent(lbArqsoV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTravaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEsphd)
                    .addComponent(lbEsphdV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTravaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLedhd)
                    .addComponent(lbLedhdV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTravaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstso)
                    .addComponent(lbEstsoV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTravaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstav)
                    .addComponent(lbEstavV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTravaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQtdram)
                    .addComponent(lbQtdramV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTravaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQtdcore)
                    .addComponent(lbQtdcoreV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTravaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSoins)
                    .addComponent(lbSoinsV, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTravaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSitpcre)
                    .addComponent(lbSitpcreV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTravaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTempcpu)
                    .addComponent(lbTempcpuV, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpTravaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVelcpu)
                    .addComponent(lbVelcpuV))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpInicializacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Inicialização"));

        lbBeeps.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbBeeps.setText("Beeps emitidos pela BIOS:");

        lbDatabios.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbDatabios.setText("Data do Sistema:");

        lbHdbios.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbHdbios.setText("Disco Rígido na BIOS:");

        lbDatabiosV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbDatabiosV.setText("---");

        lbHdbiosV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbHdbiosV.setText("---");

        lbBeepsV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbBeepsV.setText("---");

        javax.swing.GroupLayout jpInicializacaoLayout = new javax.swing.GroupLayout(jpInicializacao);
        jpInicializacao.setLayout(jpInicializacaoLayout);
        jpInicializacaoLayout.setHorizontalGroup(
            jpInicializacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInicializacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpInicializacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInicializacaoLayout.createSequentialGroup()
                        .addGroup(jpInicializacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDatabios)
                            .addComponent(lbHdbios))
                        .addGap(35, 35, 35)
                        .addGroup(jpInicializacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHdbiosV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbDatabiosV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jpInicializacaoLayout.createSequentialGroup()
                        .addComponent(lbBeeps)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbBeepsV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(83, 83, 83))))
        );
        jpInicializacaoLayout.setVerticalGroup(
            jpInicializacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInicializacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpInicializacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBeeps)
                    .addComponent(lbBeepsV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInicializacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDatabios)
                    .addComponent(lbDatabiosV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpInicializacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHdbios)
                    .addComponent(lbHdbiosV))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpNaoliga.setBorder(javax.swing.BorderFactory.createTitledBorder("Não liga"));

        lbBtpower.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbBtpower.setText("Botão de ligar do gabinete:");

        lbCabenergia.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbCabenergia.setText("Condição do cabeamento de energia:");

        lbEquipp.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbEquipp.setText("Equipamento de proteção elétrica:");

        lbVoltpsu.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbVoltpsu.setText("Voltagem da fonte de alimentação:");

        lbCabenergiaV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbCabenergiaV.setText("---");

        lbEquippV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbEquippV.setText("---");

        lbBtpowerV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbBtpowerV.setText("---");

        lbVoltpsuV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbVoltpsuV.setText("---");

        javax.swing.GroupLayout jpNaoligaLayout = new javax.swing.GroupLayout(jpNaoliga);
        jpNaoliga.setLayout(jpNaoligaLayout);
        jpNaoligaLayout.setHorizontalGroup(
            jpNaoligaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNaoligaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpNaoligaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNaoligaLayout.createSequentialGroup()
                        .addComponent(lbEquipp)
                        .addGap(21, 21, 21)
                        .addComponent(lbEquippV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpNaoligaLayout.createSequentialGroup()
                        .addGroup(jpNaoligaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCabenergia)
                            .addComponent(lbBtpower)
                            .addComponent(lbVoltpsu))
                        .addGroup(jpNaoligaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpNaoligaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpNaoligaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCabenergiaV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbBtpowerV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jpNaoligaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lbVoltpsuV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jpNaoligaLayout.setVerticalGroup(
            jpNaoligaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNaoligaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpNaoligaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBtpower)
                    .addComponent(lbBtpowerV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpNaoligaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCabenergia)
                    .addComponent(lbCabenergiaV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpNaoligaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEquipp)
                    .addComponent(lbEquippV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpNaoligaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVoltpsu)
                    .addComponent(lbVoltpsuV))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpVideo.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagem e monitor"));

        lbTela.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbTela.setText("Apresenta cores aleatórias e riscos na tela:");

        lbEstdrivervideo.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbEstdrivervideo.setText("Estado do Driver de vídeo:");

        lbEstmonitor.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbEstmonitor.setText("Estado do Monitor:");

        lbTempvga.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbTempvga.setText("Temperatura da placa de vídeo:");

        lbTipovga.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbTipovga.setText("Tipo de placa de vídeo:");

        lbTelaV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbTelaV.setText("---");

        lbEstdrivervideoV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbEstdrivervideoV.setText("---");

        lbEstmonitorV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbEstmonitorV.setText("---");

        lbTemvgaV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbTemvgaV.setText("---");

        lbTipovgaV.setFont(new java.awt.Font("Noto Sans", 3, 12)); // NOI18N
        lbTipovgaV.setText("---");

        javax.swing.GroupLayout jpVideoLayout = new javax.swing.GroupLayout(jpVideo);
        jpVideo.setLayout(jpVideoLayout);
        jpVideoLayout.setHorizontalGroup(
            jpVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVideoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTela)
                    .addComponent(lbEstdrivervideo)
                    .addComponent(lbEstmonitor)
                    .addComponent(lbTempvga)
                    .addComponent(lbTipovga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTelaV, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(lbEstdrivervideoV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbEstmonitorV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTemvgaV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTipovgaV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpVideoLayout.setVerticalGroup(
            jpVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVideoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTela)
                    .addComponent(lbTelaV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstdrivervideo)
                    .addComponent(lbEstdrivervideoV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstmonitor)
                    .addComponent(lbEstmonitorV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTempvga)
                    .addComponent(lbTemvgaV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipovga)
                    .addComponent(lbTipovgaV))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpAtributosLayout = new javax.swing.GroupLayout(jpAtributos);
        jpAtributos.setLayout(jpAtributosLayout);
        jpAtributosLayout.setHorizontalGroup(
            jpAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAtributosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpInicializacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpTrava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpDiversos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAtributosLayout.createSequentialGroup()
                        .addGroup(jpAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jpRede, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpSom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(1, 1, 1))
                    .addComponent(jpImpressao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpNaoliga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpAtributosLayout.setVerticalGroup(
            jpAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAtributosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpSom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpRede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpImpressao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpDiversos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpTrava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpInicializacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpNaoliga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        spAtributos.setViewportView(jpAtributos);

        jpConclusao.setBorder(javax.swing.BorderFactory.createTitledBorder("Conclusão"));

        lbDiagnostico.setText("Diagnóstico");

        lbCorretiva.setText("Ação Corretiva");

        taSolucao.setEditable(false);
        taSolucao.setColumns(20);
        taSolucao.setLineWrap(true);
        taSolucao.setRows(5);
        spSolucao.setViewportView(taSolucao);

        taResultado.setEditable(false);
        taResultado.setColumns(20);
        taResultado.setLineWrap(true);
        taResultado.setRows(5);
        spResultado.setViewportView(taResultado);

        javax.swing.GroupLayout jpConclusaoLayout = new javax.swing.GroupLayout(jpConclusao);
        jpConclusao.setLayout(jpConclusaoLayout);
        jpConclusaoLayout.setHorizontalGroup(
            jpConclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConclusaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpConclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCorretiva)
                    .addComponent(lbDiagnostico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpConclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spResultado)
                    .addComponent(spSolucao))
                .addContainerGap())
        );
        jpConclusaoLayout.setVerticalGroup(
            jpConclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConclusaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpConclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDiagnostico)
                    .addComponent(spResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpConclusaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCorretiva)
                    .addComponent(spSolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btFechar.setText("Fechar");
        btFechar.setToolTipText("Fecha a janela atual.");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        lbCodCaso.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbCodCaso.setText("Código Caso:");

        lbCaso.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        lbCaso.setText("---");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCodCaso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCaso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpConclusao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spAtributos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spAtributos, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpConclusao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFechar)
                    .addComponent(lbCodCaso)
                    .addComponent(lbCaso))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechar;
    private javax.swing.JPanel jpAtributos;
    private javax.swing.JPanel jpConclusao;
    private javax.swing.JPanel jpDiversos;
    private javax.swing.JPanel jpImpressao;
    private javax.swing.JPanel jpInicializacao;
    private javax.swing.JPanel jpNaoliga;
    private javax.swing.JPanel jpRede;
    private javax.swing.JPanel jpSom;
    private javax.swing.JPanel jpTrava;
    private javax.swing.JPanel jpVideo;
    private javax.swing.JLabel lbArqso;
    private javax.swing.JLabel lbArqsoV;
    private javax.swing.JLabel lbBeeps;
    private javax.swing.JLabel lbBeepsV;
    private javax.swing.JLabel lbBtpower;
    private javax.swing.JLabel lbBtpowerV;
    private javax.swing.JLabel lbCabenergia;
    private javax.swing.JLabel lbCabenergiaV;
    private javax.swing.JLabel lbCabint;
    private javax.swing.JLabel lbCabintV;
    private javax.swing.JLabel lbCaso;
    private javax.swing.JLabel lbCodCaso;
    private javax.swing.JLabel lbConimp;
    private javax.swing.JLabel lbConimpV;
    private javax.swing.JLabel lbConinternet;
    private javax.swing.JLabel lbConinternetV;
    private javax.swing.JLabel lbConrede;
    private javax.swing.JLabel lbConredeV;
    private javax.swing.JLabel lbCorretiva;
    private javax.swing.JLabel lbDatabios;
    private javax.swing.JLabel lbDatabiosV;
    private javax.swing.JLabel lbDiagnostico;
    private javax.swing.JLabel lbEnddns;
    private javax.swing.JLabel lbEnddnsV;
    private javax.swing.JLabel lbEndip;
    private javax.swing.JLabel lbEndipV;
    private javax.swing.JLabel lbEquipp;
    private javax.swing.JLabel lbEquippV;
    private javax.swing.JLabel lbEsphd;
    private javax.swing.JLabel lbEsphdV;
    private javax.swing.JLabel lbEstav;
    private javax.swing.JLabel lbEstavV;
    private javax.swing.JLabel lbEstdriverimp;
    private javax.swing.JLabel lbEstdriverimpV;
    private javax.swing.JLabel lbEstdriverrede;
    private javax.swing.JLabel lbEstdriverredeV;
    private javax.swing.JLabel lbEstdrivervideo;
    private javax.swing.JLabel lbEstdrivervideoV;
    private javax.swing.JLabel lbEstdrsomV;
    private javax.swing.JLabel lbEstgeralimp;
    private javax.swing.JLabel lbEstgeralimpV;
    private javax.swing.JLabel lbEstimpso;
    private javax.swing.JLabel lbEstimpsoV;
    private javax.swing.JLabel lbEstmonitor;
    private javax.swing.JLabel lbEstmonitorV;
    private javax.swing.JLabel lbEstpersom;
    private javax.swing.JLabel lbEstpersomV;
    private javax.swing.JLabel lbEstredeso;
    private javax.swing.JLabel lbEstredesoV;
    private javax.swing.JLabel lbEstso;
    private javax.swing.JLabel lbEstsoV;
    private javax.swing.JLabel lbEstsom;
    private javax.swing.JLabel lbFilaimp;
    private javax.swing.JLabel lbFilaimpV;
    private javax.swing.JLabel lbHdbios;
    private javax.swing.JLabel lbHdbiosV;
    private javax.swing.JLabel lbHwnovo;
    private javax.swing.JLabel lbHwnovoV;
    private javax.swing.JLabel lbInfra;
    private javax.swing.JLabel lbInfraV;
    private javax.swing.JLabel lbLedgab;
    private javax.swing.JLabel lbLedgabV;
    private javax.swing.JLabel lbLedhd;
    private javax.swing.JLabel lbLedhdV;
    private javax.swing.JLabel lbLedimp;
    private javax.swing.JLabel lbLedimpV;
    private javax.swing.JLabel lbMsgerro;
    private javax.swing.JLabel lbMsgerroV;
    private javax.swing.JLabel lbNivelcar;
    private javax.swing.JLabel lbNivelcarV;
    private javax.swing.JLabel lbQtdcore;
    private javax.swing.JLabel lbQtdcoreV;
    private javax.swing.JLabel lbQtdram;
    private javax.swing.JLabel lbQtdramV;
    private javax.swing.JLabel lbQtdsom;
    private javax.swing.JLabel lbQtdsomV;
    private javax.swing.JLabel lbRj45;
    private javax.swing.JLabel lbRj45V;
    private javax.swing.JLabel lbSitpcre;
    private javax.swing.JLabel lbSitpcreV;
    private javax.swing.JLabel lbSitsom;
    private javax.swing.JLabel lbSitsomV;
    private javax.swing.JLabel lbSoins;
    private javax.swing.JLabel lbSoinsV;
    private javax.swing.JLabel lbSujgab;
    private javax.swing.JLabel lbSujgabV;
    private javax.swing.JLabel lbTela;
    private javax.swing.JLabel lbTelaV;
    private javax.swing.JLabel lbTempcpu;
    private javax.swing.JLabel lbTempcpuV;
    private javax.swing.JLabel lbTempvga;
    private javax.swing.JLabel lbTemvgaV;
    private javax.swing.JLabel lbTipoimp;
    private javax.swing.JLabel lbTipoimsoV;
    private javax.swing.JLabel lbTipovga;
    private javax.swing.JLabel lbTipovgaV;
    private javax.swing.JLabel lbVelcpu;
    private javax.swing.JLabel lbVelcpuV;
    private javax.swing.JLabel lbVoltpsu;
    private javax.swing.JLabel lbVoltpsuV;
    private javax.swing.JScrollPane spAtributos;
    private javax.swing.JScrollPane spResultado;
    private javax.swing.JScrollPane spSolucao;
    private javax.swing.JTextArea taResultado;
    private javax.swing.JTextArea taSolucao;
    // End of variables declaration//GEN-END:variables
    private Caso caso;
    
    private void setCaso() {
       
        lbCaso.setText("" + caso.getIdCaso());
        
        if(caso.getEstDriversom() != null) lbEstdrsomV.setText(caso.getEstDriversom());
        if(caso.getEstDispositivoaudio() != null)lbEstpersomV.setText(caso.getEstDispositivoaudio());
        if(caso.getQtdDispositivoaudio() != null)lbQtdsomV.setText(caso.getQtdDispositivoaudio());
        if(caso.getSitSomnaofunciona() != null)lbSitsomV.setText(caso.getSitSomnaofunciona());
        
        if(caso.getGabSujeira() != null)lbSujgabV.setText(caso.getGabSujeira());
        if(caso.getGabCabeamentointerno() != null)lbCabintV.setText(caso.getGabCabeamentointerno());
        if(caso.getMsgErro() != null)lbMsgerroV.setText(caso.getMsgErro());
        if(caso.getHwNovoinstalado() != null)lbHwnovoV.setText(caso.getHwNovoinstalado());
        if(caso.getGabLedfuncionamento()!= null)lbLedgabV.setText(caso.getGabLedfuncionamento());
        
        if(caso.getMonRiscoscores() != null)lbTelaV.setText(caso.getMonRiscoscores());
        if(caso.getEstDrivervideo() != null)lbEstdrivervideoV.setText(caso.getEstDrivervideo());
        if(caso.getEstMonitor() != null)lbEstmonitorV.setText(caso.getEstMonitor());
        if(caso.getTempVga() != null)lbTemvgaV.setText(String.valueOf(caso.getTempVga()));
        if(caso.getTipoVga() != null)lbTipovgaV.setText(caso.getTipoVga());
        
        if(caso.getEstSoimpressora()!= null)lbEstimpsoV.setText(caso.getEstSoimpressora());
        if(caso.getEstDriverimpressora() != null)lbEstdriverimpV.setText(caso.getEstDriverimpressora());
        if(caso.getEstLedimpressora() != null)lbLedimpV.setText(caso.getEstLedimpressora());
        if(caso.getEstGeralimpressora() != null)lbEstgeralimpV.setText(caso.getEstGeralimpressora());
        if(caso.getNivelCartuchoimpressora() != null)lbNivelcarV.setText(caso.getNivelCartuchoimpressora());
        if(caso.getFilaImpressao() != null)lbFilaimpV.setText(caso.getFilaImpressao());
        if(caso.getTipoConexaoimpressora() != null)lbConimpV.setText(caso.getTipoConexaoimpressora());
        if(caso.getTipoSoimpressora() != null)lbTipoimsoV.setText(caso.getTipoSoimpressora());
        
        if(caso.getBipBios() != null)lbBeepsV.setText(caso.getBipBios());
        if(caso.getDataSistema() != null)lbDatabiosV.setText(caso.getDataSistema());
        if(caso.getHdBios() != null)lbHdbiosV.setText(caso.getHdBios());
        
        if(caso.getSoArquitetura() != null)lbArqsoV.setText("" + caso.getSoArquitetura() + " bits");
        if(caso.getHdEspacolivre() != null)lbEsphdV.setText("" + caso.getHdEspacolivre() + " Gbs");
        if(caso.getEstLedhd() != null)lbLedhdV.setText(caso.getEstLedhd());
        if(caso.getEstSistemaoperacional() != null)lbEstsoV.setText(caso.getEstSistemaoperacional());
        if(caso.getEstAntivirus() != null)lbEstavV.setText(caso.getEstAntivirus());
        if(caso.getQtdRam() != null)lbQtdramV.setText("" + caso.getQtdRam() + " Gbs");
        if(caso.getQtdCores() != null)lbQtdcoreV.setText("" + caso.getQtdCores());
        if(caso.getSoInstalado() != null)lbSoinsV.setText(caso.getSoInstalado());
        if(caso.getPcReinicia() != null)lbSitpcreV.setText(caso.getPcReinicia());
        if(caso.getTempCpu() != null)lbTempcpuV.setText("" + caso.getTempCpu());
        if(caso.getCpuVelocidade() != null)lbVelcpuV.setText("" + caso.getCpuVelocidade() + " Ghz");
        
        if(caso.getGabBotaopower() != null)lbBtpowerV.setText(caso.getGabBotaopower());
        if(caso.getCondCabeamentoenergia() != null)lbCabenergiaV.setText(caso.getCondCabeamentoenergia());
        if(caso.getEquipProtecaoenergia() != null)lbEquippV.setText(caso.getEquipProtecaoenergia());
        if(caso.getPsuVoltagem() != null)lbVoltpsuV.setText(caso.getPsuVoltagem());
        
        if(caso.getEndDns() != null)lbEnddnsV.setText(caso.getEndDns());
        if(caso.getEndIp() != null)lbEndipV.setText(caso.getEndIp());
        if(caso.getEstConexaorede() != null)lbEstredesoV.setText(caso.getEstConexaorede());
        if(caso.getEstRjConector() != null)lbRj45V.setText(caso.getEstRjConector());
        if(caso.getEstDriverrede() != null)lbEstdriverredeV.setText(caso.getEstDriverrede());
        if(caso.getInfraRede() != null)lbInfraV.setText(caso.getInfraRede());
        if(caso.getTipoConexaointernet() != null)lbConinternetV.setText(caso.getTipoConexaointernet());
        if(caso.getTipoConexaorede() != null)lbConredeV.setText(caso.getTipoConexaorede());
        
        taResultado.setText(caso.getResultado().getDesResultado());
        taSolucao.setText(caso.getSolucao().getDesSolucao());

    }
    
}
