/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Beans.Ocorrencia;
import DAO.DAOOcorrencia;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wanderson
 */
public class JFprincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFprincipal
     */
    public JFprincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        ((DefaultTableCellRenderer)jtCasos.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
        jtCasos.getColumnModel().getColumn(0).setPreferredWidth(5);
        jtCasos.getColumnModel().getColumn(1).setPreferredWidth(220);
        jtCasos.getColumnModel().getColumn(2).setPreferredWidth(45);
        jtCasos.getColumnModel().getColumn(3).setPreferredWidth(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spPrincipal = new javax.swing.JScrollPane();
        jtCasos = new javax.swing.JTable();
        btAbrir = new javax.swing.JButton();
        lbOcorrencias = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        mbPrincipal = new javax.swing.JMenuBar();
        jmArquivo = new javax.swing.JMenu();
        miSair = new javax.swing.JMenuItem();
        jmCadastro = new javax.swing.JMenu();
        miCliente = new javax.swing.JMenuItem();
        miTecnico = new javax.swing.JMenuItem();
        jsSeparador1 = new javax.swing.JPopupMenu.Separator();
        miOcorrencia = new javax.swing.JMenuItem();
        jsSeparador2 = new javax.swing.JPopupMenu.Separator();
        miCasos = new javax.swing.JMenuItem();
        jmConsulta = new javax.swing.JMenu();
        miConClientes = new javax.swing.JMenuItem();
        miConTecnicos = new javax.swing.JMenuItem();
        jSeparador3 = new javax.swing.JPopupMenu.Separator();
        miConOcorrencias = new javax.swing.JMenuItem();
        jSeparador4 = new javax.swing.JPopupMenu.Separator();
        miConCasos = new javax.swing.JMenuItem();
        jmAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RBC - Manutenção em Informática");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jtCasos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Problema", "Data Abertura", "Prioridade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtCasos.setToolTipText("Tabela de ocorrência abertas no sistema, selecione somente uma e use o botão abaixo para abrí-la.");
        spPrincipal.setViewportView(jtCasos);

        btAbrir.setText("Abrir Ocorência");
        btAbrir.setToolTipText("Abrir ocorrência selecionada na tabela acima.");
        btAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirActionPerformed(evt);
            }
        });

        lbOcorrencias.setText("Ocorrências em aberto:");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logoRBC.png"))); // NOI18N

        jmArquivo.setText("Arquivo");

        miSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        miSair.setText("Sair");
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        jmArquivo.add(miSair);

        mbPrincipal.add(jmArquivo);

        jmCadastro.setText("Cadastro");

        miCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        miCliente.setText("Clientes");
        miCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClienteActionPerformed(evt);
            }
        });
        jmCadastro.add(miCliente);

        miTecnico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        miTecnico.setText("Técnicos");
        miTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTecnicoActionPerformed(evt);
            }
        });
        jmCadastro.add(miTecnico);
        jmCadastro.add(jsSeparador1);

        miOcorrencia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        miOcorrencia.setText("Ocorrências");
        miOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOcorrenciaActionPerformed(evt);
            }
        });
        jmCadastro.add(miOcorrencia);
        jmCadastro.add(jsSeparador2);

        miCasos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        miCasos.setText("Casos");
        miCasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCasosActionPerformed(evt);
            }
        });
        jmCadastro.add(miCasos);

        mbPrincipal.add(jmCadastro);

        jmConsulta.setText("Consulta");

        miConClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        miConClientes.setText("Clientes");
        miConClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConClientesActionPerformed(evt);
            }
        });
        jmConsulta.add(miConClientes);

        miConTecnicos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        miConTecnicos.setText("Técnicos");
        miConTecnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConTecnicosActionPerformed(evt);
            }
        });
        jmConsulta.add(miConTecnicos);
        jmConsulta.add(jSeparador3);

        miConOcorrencias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        miConOcorrencias.setText("Ocorrências");
        miConOcorrencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConOcorrenciasActionPerformed(evt);
            }
        });
        jmConsulta.add(miConOcorrencias);
        jmConsulta.add(jSeparador4);

        miConCasos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        miConCasos.setText("Casos");
        miConCasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConCasosActionPerformed(evt);
            }
        });
        jmConsulta.add(miConCasos);

        mbPrincipal.add(jmConsulta);

        jmAjuda.setText("Ajuda");
        jmAjuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmAjudaMousePressed(evt);
            }
        });
        mbPrincipal.add(jmAjuda);

        setJMenuBar(mbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblLogo)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbOcorrencias)
                            .addComponent(spPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btAbrir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbOcorrencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAbrir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_miSairActionPerformed

    private void miClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClienteActionPerformed
        // TODO add your handling code here:
        cadCliente = new JFCadCliente();
        cadCliente.setLocationRelativeTo(this);
        cadCliente.setVisible(true);
    }//GEN-LAST:event_miClienteActionPerformed

    private void miTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTecnicoActionPerformed
        // TODO add your handling code here:
        cadTecnico = new JFCadTecnico();
        cadTecnico.setLocationRelativeTo(this);
        cadTecnico.setVisible(true);
    }//GEN-LAST:event_miTecnicoActionPerformed

    private void miOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOcorrenciaActionPerformed
        // TODO add your handling code here:
        cadOcorrencia = new JFCadOcorrencia();
        cadOcorrencia.setLocationRelativeTo(this);
        cadOcorrencia.setVisible(true);
    }//GEN-LAST:event_miOcorrenciaActionPerformed

    private void miCasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCasosActionPerformed
        // TODO add your handling code here:
        cadCaso = new JFCadCaso(null);
        cadCaso.setLocationRelativeTo(this);
        cadCaso.setVisible(true);
    }//GEN-LAST:event_miCasosActionPerformed

    private void btAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirActionPerformed
        // TODO add your handling code here:
        //fazer mais coisas aqui depois
        editarOcorrencia();
    }//GEN-LAST:event_btAbrirActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        listarOcorrencias();
    }//GEN-LAST:event_formWindowGainedFocus

    private void miConCasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConCasosActionPerformed
        // TODO add your handling code here:
        listaCaso = new JFListaCaso();
        listaCaso.setLocationRelativeTo(this);
        listaCaso.setVisible(true);
    }//GEN-LAST:event_miConCasosActionPerformed

    private void miConTecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConTecnicosActionPerformed
        // TODO add your handling code here:
        listaTecnico = new JFListaTecnico();
        listaTecnico.setLocationRelativeTo(this);
        listaTecnico.setVisible(true);
    }//GEN-LAST:event_miConTecnicosActionPerformed

    private void miConClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConClientesActionPerformed
        // TODO add your handling code here:
        listaCliente = new JFListaCliente();
        listaCliente.setLocationRelativeTo(this);
        listaCliente.setVisible(true);
    }//GEN-LAST:event_miConClientesActionPerformed

    private void miConOcorrenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConOcorrenciasActionPerformed
        // TODO add your handling code here:
        listaOcorrencia = new JFListaOcorrencia();
        listaOcorrencia.setLocationRelativeTo(this);
        listaOcorrencia.setVisible(true);
    }//GEN-LAST:event_miConOcorrenciasActionPerformed

    private void jmAjudaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAjudaMousePressed
        // TODO add your handling code here:
        ajuda = new JFAjuda();
        ajuda.setLocationRelativeTo(this);
        ajuda.setVisible(true);
    }//GEN-LAST:event_jmAjudaMousePressed

    /**
     * @param args the command line arguments
     *
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form *
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFprincipal().setVisible(true);
            }
        });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbrir;
    private javax.swing.JPopupMenu.Separator jSeparador3;
    private javax.swing.JPopupMenu.Separator jSeparador4;
    private javax.swing.JMenu jmAjuda;
    private javax.swing.JMenu jmArquivo;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmConsulta;
    private javax.swing.JPopupMenu.Separator jsSeparador1;
    private javax.swing.JPopupMenu.Separator jsSeparador2;
    private javax.swing.JTable jtCasos;
    private javax.swing.JLabel lbOcorrencias;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JMenuBar mbPrincipal;
    private javax.swing.JMenuItem miCasos;
    private javax.swing.JMenuItem miCliente;
    private javax.swing.JMenuItem miConCasos;
    private javax.swing.JMenuItem miConClientes;
    private javax.swing.JMenuItem miConOcorrencias;
    private javax.swing.JMenuItem miConTecnicos;
    private javax.swing.JMenuItem miOcorrencia;
    private javax.swing.JMenuItem miSair;
    private javax.swing.JMenuItem miTecnico;
    private javax.swing.JScrollPane spPrincipal;
    // End of variables declaration//GEN-END:variables
    private JFCadCliente cadCliente;
    private JFCadOcorrencia cadOcorrencia;
    private JFCadTecnico cadTecnico;
    private JFCadCaso cadCaso;
    private JFEditarOcorrencia editaOcorrencia;
    private JFListaTecnico listaTecnico;
    private JFListaCliente listaCliente;
    private JFListaOcorrencia listaOcorrencia;
    private JFListaCaso listaCaso;
    private JFAjuda ajuda;
    private HashMap hmOcorrencia;
    
    private void listarOcorrencias() {
        
        DefaultTableModel dtm = (DefaultTableModel)jtCasos.getModel();
        dtm.setNumRows(0);
        
        DAOOcorrencia daoOcorrencia = new DAOOcorrencia();
        Ocorrencia ocorrencia;
        List listaOco;
        
        try {
            listaOco = daoOcorrencia.listar("where estOcorrencia=0 order by priOcorrencia desc");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Houve algum problema com a listagem das ocorrências, detalhes:\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);            
            return;
        }
        
        SimpleDateFormat df;
        df = new SimpleDateFormat("dd/MM/yyyy");
        String pri;
        hmOcorrencia = new HashMap();
        
        for(int i=0; i<listaOco.size(); i++) { //insere resultado nas tabelas
           
            ocorrencia = (Ocorrencia)listaOco.get(i);
            hmOcorrencia.put(ocorrencia.getIdOcorrencia(), ocorrencia);
           
            if(ocorrencia.getPriOcorrencia() == 0){
                pri = "Baixa";
            } else {
                if (ocorrencia.getPriOcorrencia() == 1) {
                    pri = "Normal";
                } else {
                    pri = "Alta";
                }
            }
           
            String problema = ocorrencia.getProbOcorrencia();
            
            if (problema.equals("")) problema = "Não informado"; 
           
            dtm.addRow(new Object[]{ocorrencia.getIdOcorrencia(), problema, df.format(ocorrencia.getDtAbertura()), pri});     
            
        }
    }
    
    private void editarOcorrencia() {
        
        DefaultTableModel dtm = (DefaultTableModel)jtCasos.getModel();
        int[] l = jtCasos.getSelectedRows();
        
        if(l.length == 1) {
            int idOcorrencia = (Integer)dtm.getValueAt(l[0], 0);
            Ocorrencia oco = (Ocorrencia)hmOcorrencia.get(idOcorrencia);
            editaOcorrencia = new JFEditarOcorrencia(oco);
            editaOcorrencia.setLocationRelativeTo(this);
            editaOcorrencia.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione no minímo/máximo uma ocorrência!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
}
