package Beans;
// Generated 03/10/2015 21:05:39 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import jcolibri.cbrcore.Attribute;

/**
 * Caso generated by hbm2java
 */
public class Caso implements jcolibri.cbrcore.CaseComponent {


     private Integer idCaso;
     private Resultado resultado;
     private Solucao solucao;
     private String endDns;
     private String endIp;
     private String estConexaorede;
     private String estDriverrede;
     private String estRjConector;
     private String tipoConexaorede;
     private String tipoConexaointernet;
     private String infraRede;
     private String estSoimpressora;
     private String estDriverimpressora;
     private String estLedimpressora;
     private String estGeralimpressora;
     private String tipoSoimpressora;
     private String tipoConexaoimpressora;
     private String nivelCartuchoimpressora;
     private String filaImpressao;
     private String qtdDispositivoaudio;
     private String estDriversom;
     private String estDispositivoaudio;
     private String sitSomnaofunciona;
     private Integer soArquitetura;
     private Double hdEspacolivre;
     private String hwNovoinstalado;
     private String msgErro;
     private Double qtdRam;
     private String estLedhd;
     private String gabSujeira;
     private Integer qtdCores;
     private String soInstalado;
     private String estAntivirus;
     private String estSistemaoperacional;
     private Double cpuVelocidade;
     private String bipBios;
     private String dataSistema;
     private String hdBios;
     private String gabLedfuncionamento;
     private String estMonitor;
     private Double tempCpu;
     private String gabBotaopower;
     private String gabCabeamentointerno;
     private String condCabeamentoenergia;
     private String psuVoltagem;
     private String equipProtecaoenergia;
     private String monRiscoscores;
     private Double tempVga;
     private String tipoVga;
     private String estDrivervideo;
     private String pcReinicia;
     private Set ocorrencias = new HashSet(0);

    public Caso() {
    }
	
    public Caso(Resultado resultado, Solucao solucao) {
        this.resultado = resultado;
        this.solucao = solucao;
    }
    
    public Caso(Resultado resultado, Solucao solucao, String endDns, String endIp, String estConexaorede, String estDriverrede, String estRjConector, String tipoConexaorede, String tipoConexaointernet, String infraRede, String estSoimpressora, String estDriverimpressora, String estLedimpressora, String estGeralimpressora, String tipoSoimpressora, String tipoConexaoimpressora, String nivelCartuchoimpressora, String filaImpressao, String qtdDispositivoaudio, String estDriversom, String estDispositivoaudio, String sitSomnaofunciona, Integer soArquitetura, Double hdEspacolivre, String hwNovoinstalado, String msgErro, Double qtdRam, String estLedhd, String gabSujeira, Integer qtdCores, String soInstalado, String estAntivirus, String estSistemaoperacional, Double cpuVelocidade, String bipBios, String dataSistema, String hdBios, String gabLedfuncionamento, String estMonitor, Double tempCpu, String gabBotaopower, String gabCabeamentointerno, String condCabeamentoenergia, String psuVoltagem, String equipProtecaoenergia, String monRiscoscores, Double tempVga, String tipoVga, String estDrivervideo, String pcReinicia, Set ocorrencias) {
       this.resultado = resultado;
       this.solucao = solucao;
       this.endDns = endDns;
       this.endIp = endIp;
       this.estConexaorede = estConexaorede;
       this.estDriverrede = estDriverrede;
       this.estRjConector = estRjConector;
       this.tipoConexaorede = tipoConexaorede;
       this.tipoConexaointernet = tipoConexaointernet;
       this.infraRede = infraRede;
       this.estSoimpressora = estSoimpressora;
       this.estDriverimpressora = estDriverimpressora;
       this.estLedimpressora = estLedimpressora;
       this.estGeralimpressora = estGeralimpressora;
       this.tipoSoimpressora = tipoSoimpressora;
       this.tipoConexaoimpressora = tipoConexaoimpressora;
       this.nivelCartuchoimpressora = nivelCartuchoimpressora;
       this.filaImpressao = filaImpressao;
       this.qtdDispositivoaudio = qtdDispositivoaudio;
       this.estDriversom = estDriversom;
       this.estDispositivoaudio = estDispositivoaudio;
       this.sitSomnaofunciona = sitSomnaofunciona;
       this.soArquitetura = soArquitetura;
       this.hdEspacolivre = hdEspacolivre;
       this.hwNovoinstalado = hwNovoinstalado;
       this.msgErro = msgErro;
       this.qtdRam = qtdRam;
       this.estLedhd = estLedhd;
       this.gabSujeira = gabSujeira;
       this.qtdCores = qtdCores;
       this.soInstalado = soInstalado;
       this.estAntivirus = estAntivirus;
       this.estSistemaoperacional = estSistemaoperacional;
       this.cpuVelocidade = cpuVelocidade;
       this.bipBios = bipBios;
       this.dataSistema = dataSistema;
       this.hdBios = hdBios;
       this.gabLedfuncionamento = gabLedfuncionamento;
       this.estMonitor = estMonitor;
       this.tempCpu = tempCpu;
       this.gabBotaopower = gabBotaopower;
       this.gabCabeamentointerno = gabCabeamentointerno;
       this.condCabeamentoenergia = condCabeamentoenergia;
       this.psuVoltagem = psuVoltagem;
       this.equipProtecaoenergia = equipProtecaoenergia;
       this.monRiscoscores = monRiscoscores;
       this.tempVga = tempVga;
       this.tipoVga = tipoVga;
       this.estDrivervideo = estDrivervideo;
       this.pcReinicia = pcReinicia;
       this.ocorrencias = ocorrencias;
    }
    
  
     @Override
    public Attribute getIdAttribute() {
        return new Attribute("idCaso", this.getClass());    
    }
   
    public Integer getIdCaso() {
        return this.idCaso;
    }
    
    public void setIdCaso(Integer idCaso) {
        this.idCaso = idCaso;
    }
    public Resultado getResultado() {
        return this.resultado;
    }
    
    public void setResultado(Resultado resultado) {
        this.resultado = resultado;
    }
    public Solucao getSolucao() {
        return this.solucao;
    }
    
    public void setSolucao(Solucao solucao) {
        this.solucao = solucao;
    }
    public String getEndDns() {
        return this.endDns;
    }
    
    public void setEndDns(String endDns) {
        this.endDns = endDns;
    }
    public String getEndIp() {
        return this.endIp;
    }
    
    public void setEndIp(String endIp) {
        this.endIp = endIp;
    }
    public String getEstConexaorede() {
        return this.estConexaorede;
    }
    
    public void setEstConexaorede(String estConexaorede) {
        this.estConexaorede = estConexaorede;
    }
    public String getEstDriverrede() {
        return this.estDriverrede;
    }
    
    public void setEstDriverrede(String estDriverrede) {
        this.estDriverrede = estDriverrede;
    }
    public String getEstRjConector() {
        return this.estRjConector;
    }
    
    public void setEstRjConector(String estRjConector) {
        this.estRjConector = estRjConector;
    }
    public String getTipoConexaorede() {
        return this.tipoConexaorede;
    }
    
    public void setTipoConexaorede(String tipoConexaorede) {
        this.tipoConexaorede = tipoConexaorede;
    }
    public String getTipoConexaointernet() {
        return this.tipoConexaointernet;
    }
    
    public void setTipoConexaointernet(String tipoConexaointernet) {
        this.tipoConexaointernet = tipoConexaointernet;
    }
    public String getInfraRede() {
        return this.infraRede;
    }
    
    public void setInfraRede(String infraRede) {
        this.infraRede = infraRede;
    }
    public String getEstSoimpressora() {
        return this.estSoimpressora;
    }
    
    public void setEstSoimpressora(String estSoimpressora) {
        this.estSoimpressora = estSoimpressora;
    }
    public String getEstDriverimpressora() {
        return this.estDriverimpressora;
    }
    
    public void setEstDriverimpressora(String estDriverimpressora) {
        this.estDriverimpressora = estDriverimpressora;
    }
    public String getEstLedimpressora() {
        return this.estLedimpressora;
    }
    
    public void setEstLedimpressora(String estLedimpressora) {
        this.estLedimpressora = estLedimpressora;
    }
    public String getEstGeralimpressora() {
        return this.estGeralimpressora;
    }
    
    public void setEstGeralimpressora(String estGeralimpressora) {
        this.estGeralimpressora = estGeralimpressora;
    }
    public String getTipoSoimpressora() {
        return this.tipoSoimpressora;
    }
    
    public void setTipoSoimpressora(String tipoSoimpressora) {
        this.tipoSoimpressora = tipoSoimpressora;
    }
    public String getTipoConexaoimpressora() {
        return this.tipoConexaoimpressora;
    }
    
    public void setTipoConexaoimpressora(String tipoConexaoimpressora) {
        this.tipoConexaoimpressora = tipoConexaoimpressora;
    }
    public String getNivelCartuchoimpressora() {
        return this.nivelCartuchoimpressora;
    }
    
    public void setNivelCartuchoimpressora(String nivelCartuchoimpressora) {
        this.nivelCartuchoimpressora = nivelCartuchoimpressora;
    }
    public String getFilaImpressao() {
        return this.filaImpressao;
    }
    
    public void setFilaImpressao(String filaImpressao) {
        this.filaImpressao = filaImpressao;
    }
    public String getQtdDispositivoaudio() {
        return this.qtdDispositivoaudio;
    }
    
    public void setQtdDispositivoaudio(String qtdDispositivoaudio) {
        this.qtdDispositivoaudio = qtdDispositivoaudio;
    }
    public String getEstDriversom() {
        return this.estDriversom;
    }
    
    public void setEstDriversom(String estDriversom) {
        this.estDriversom = estDriversom;
    }
    public String getEstDispositivoaudio() {
        return this.estDispositivoaudio;
    }
    
    public void setEstDispositivoaudio(String estDispositivoaudio) {
        this.estDispositivoaudio = estDispositivoaudio;
    }
    public String getSitSomnaofunciona() {
        return this.sitSomnaofunciona;
    }
    
    public void setSitSomnaofunciona(String sitSomnaofunciona) {
        this.sitSomnaofunciona = sitSomnaofunciona;
    }
    public Integer getSoArquitetura() {
        return this.soArquitetura;
    }
    
    public void setSoArquitetura(Integer soArquitetura) {
        this.soArquitetura = soArquitetura;
    }
    public Double getHdEspacolivre() {
        return this.hdEspacolivre;
    }
    
    public void setHdEspacolivre(Double hdEspacolivre) {
        this.hdEspacolivre = hdEspacolivre;
    }
    public String getHwNovoinstalado() {
        return this.hwNovoinstalado;
    }
    
    public void setHwNovoinstalado(String hwNovoinstalado) {
        this.hwNovoinstalado = hwNovoinstalado;
    }
    public String getMsgErro() {
        return this.msgErro;
    }
    
    public void setMsgErro(String msgErro) {
        this.msgErro = msgErro;
    }
    public Double getQtdRam() {
        return this.qtdRam;
    }
    
    public void setQtdRam(Double qtdRam) {
        this.qtdRam = qtdRam;
    }
    public String getEstLedhd() {
        return this.estLedhd;
    }
    
    public void setEstLedhd(String estLedhd) {
        this.estLedhd = estLedhd;
    }
    public String getGabSujeira() {
        return this.gabSujeira;
    }
    
    public void setGabSujeira(String gabSujeira) {
        this.gabSujeira = gabSujeira;
    }
    public Integer getQtdCores() {
        return this.qtdCores;
    }
    
    public void setQtdCores(Integer qtdCores) {
        this.qtdCores = qtdCores;
    }
    public String getSoInstalado() {
        return this.soInstalado;
    }
    
    public void setSoInstalado(String soInstalado) {
        this.soInstalado = soInstalado;
    }
    public String getEstAntivirus() {
        return this.estAntivirus;
    }
    
    public void setEstAntivirus(String estAntivirus) {
        this.estAntivirus = estAntivirus;
    }
    public String getEstSistemaoperacional() {
        return this.estSistemaoperacional;
    }
    
    public void setEstSistemaoperacional(String estSistemaoperacional) {
        this.estSistemaoperacional = estSistemaoperacional;
    }
    public Double getCpuVelocidade() {
        return this.cpuVelocidade;
    }
    
    public void setCpuVelocidade(Double cpuVelocidade) {
        this.cpuVelocidade = cpuVelocidade;
    }
    public String getBipBios() {
        return this.bipBios;
    }
    
    public void setBipBios(String bipBios) {
        this.bipBios = bipBios;
    }
    public String getDataSistema() {
        return this.dataSistema;
    }
    
    public void setDataSistema(String dataSistema) {
        this.dataSistema = dataSistema;
    }
    public String getHdBios() {
        return this.hdBios;
    }
    
    public void setHdBios(String hdBios) {
        this.hdBios = hdBios;
    }
    public String getGabLedfuncionamento() {
        return this.gabLedfuncionamento;
    }
    
    public void setGabLedfuncionamento(String gabLedfuncionamento) {
        this.gabLedfuncionamento = gabLedfuncionamento;
    }
    public String getEstMonitor() {
        return this.estMonitor;
    }
    
    public void setEstMonitor(String estMonitor) {
        this.estMonitor = estMonitor;
    }
    public Double getTempCpu() {
        return this.tempCpu;
    }
    
    public void setTempCpu(Double tempCpu) {
        this.tempCpu = tempCpu;
    }
    public String getGabBotaopower() {
        return this.gabBotaopower;
    }
    
    public void setGabBotaopower(String gabBotaopower) {
        this.gabBotaopower = gabBotaopower;
    }
    public String getGabCabeamentointerno() {
        return this.gabCabeamentointerno;
    }
    
    public void setGabCabeamentointerno(String gabCabeamentointerno) {
        this.gabCabeamentointerno = gabCabeamentointerno;
    }
    public String getCondCabeamentoenergia() {
        return this.condCabeamentoenergia;
    }
    
    public void setCondCabeamentoenergia(String condCabeamentoenergia) {
        this.condCabeamentoenergia = condCabeamentoenergia;
    }
    public String getPsuVoltagem() {
        return this.psuVoltagem;
    }
    
    public void setPsuVoltagem(String psuVoltagem) {
        this.psuVoltagem = psuVoltagem;
    }
    public String getEquipProtecaoenergia() {
        return this.equipProtecaoenergia;
    }
    
    public void setEquipProtecaoenergia(String equipProtecaoenergia) {
        this.equipProtecaoenergia = equipProtecaoenergia;
    }
    public String getMonRiscoscores() {
        return this.monRiscoscores;
    }
    
    public void setMonRiscoscores(String monRiscoscores) {
        this.monRiscoscores = monRiscoscores;
    }
    public Double getTempVga() {
        return this.tempVga;
    }
    
    public void setTempVga(Double tempVga) {
        this.tempVga = tempVga;
    }
    public String getTipoVga() {
        return this.tipoVga;
    }
    
    public void setTipoVga(String tipoVga) {
        this.tipoVga = tipoVga;
    }
    public String getEstDrivervideo() {
        return this.estDrivervideo;
    }
    
    public void setEstDrivervideo(String estDrivervideo) {
        this.estDrivervideo = estDrivervideo;
    }
    public String getPcReinicia() {
        return this.pcReinicia;
    }
    
    public void setPcReinicia(String pcReinicia) {
        this.pcReinicia = pcReinicia;
    }
    public Set getOcorrencias() {
        return this.ocorrencias;
    }
    
    public void setOcorrencias(Set ocorrencias) {
        this.ocorrencias = ocorrencias;
    }


}


