package Beans;
// Generated 03/10/2015 21:05:39 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String nmCliente;
     private String cpfCliente;
     private String endCliente;
     private String telCliente;
     private String emailCliente;
     private Set ocorrencias = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String nmCliente) {
        this.nmCliente = nmCliente;
    }
    public Cliente(String nmCliente, String cpfCliente, String endCliente, String telCliente, String emailCliente, Set ocorrencias) {
       this.nmCliente = nmCliente;
       this.cpfCliente = cpfCliente;
       this.endCliente = endCliente;
       this.telCliente = telCliente;
       this.emailCliente = emailCliente;
       this.ocorrencias = ocorrencias;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNmCliente() {
        return this.nmCliente;
    }
    
    public void setNmCliente(String nmCliente) {
        this.nmCliente = nmCliente;
    }
    public String getCpfCliente() {
        return this.cpfCliente;
    }
    
    public void setCpfCliente(String cpfCliente) {
        this.cpfCliente = cpfCliente;
    }
    public String getEndCliente() {
        return this.endCliente;
    }
    
    public void setEndCliente(String endCliente) {
        this.endCliente = endCliente;
    }
    public String getTelCliente() {
        return this.telCliente;
    }
    
    public void setTelCliente(String telCliente) {
        this.telCliente = telCliente;
    }
    public String getEmailCliente() {
        return this.emailCliente;
    }
    
    public void setEmailCliente(String emailCliente) {
        this.emailCliente = emailCliente;
    }
    public Set getOcorrencias() {
        return this.ocorrencias;
    }
    
    public void setOcorrencias(Set ocorrencias) {
        this.ocorrencias = ocorrencias;
    }




}


