package Beans;
// Generated 03/10/2015 21:05:39 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Ocorrencia generated by hbm2java
 */
public class Ocorrencia  implements java.io.Serializable {


     private Integer idOcorrencia;
     private Cliente cliente;
     private Caso caso;
     private Tecnico tecnico;
     private Date dtAbertura;
     private Date dtFechamento;
     private Date tmpConserto;
     private BigDecimal valorConserto;
     private int priOcorrencia;
     private int estOcorrencia;
     private String obsOcorrencia;
     private String probOcorrencia;
     private String desEquipamento;

    public Ocorrencia() {
    }

	
    public Ocorrencia(Cliente cliente, Date dtAbertura, int priOcorrencia, int estOcorrencia) {
        this.cliente = cliente;
        this.dtAbertura = dtAbertura;
        this.priOcorrencia = priOcorrencia;
        this.estOcorrencia = estOcorrencia;
    }
    public Ocorrencia(Cliente cliente, Caso caso, Tecnico tecnico, Date dtAbertura, Date dtFechamento, Date tmpConserto, BigDecimal valorConserto, int priOcorrencia, int estOcorrencia, String obsOcorrencia, String probOcorrencia, String desEquipamento) {
       this.cliente = cliente;
       this.caso = caso;
       this.tecnico = tecnico;
       this.dtAbertura = dtAbertura;
       this.dtFechamento = dtFechamento;
       this.tmpConserto = tmpConserto;
       this.valorConserto = valorConserto;
       this.priOcorrencia = priOcorrencia;
       this.estOcorrencia = estOcorrencia;
       this.obsOcorrencia = obsOcorrencia;
       this.probOcorrencia = probOcorrencia;
       this.desEquipamento = desEquipamento;
    }
   
    public Integer getIdOcorrencia() {
        return this.idOcorrencia;
    }
    
    public void setIdOcorrencia(Integer idOcorrencia) {
        this.idOcorrencia = idOcorrencia;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Caso getCaso() {
        return this.caso;
    }
    
    public void setCaso(Caso caso) {
        this.caso = caso;
    }
    public Tecnico getTecnico() {
        return this.tecnico;
    }
    
    public void setTecnico(Tecnico tecnico) {
        this.tecnico = tecnico;
    }
    public Date getDtAbertura() {
        return this.dtAbertura;
    }
    
    public void setDtAbertura(Date dtAbertura) {
        this.dtAbertura = dtAbertura;
    }
    public Date getDtFechamento() {
        return this.dtFechamento;
    }
    
    public void setDtFechamento(Date dtFechamento) {
        this.dtFechamento = dtFechamento;
    }
    public Date getTmpConserto() {
        return this.tmpConserto;
    }
    
    public void setTmpConserto(Date tmpConserto) {
        this.tmpConserto = tmpConserto;
    }
    public BigDecimal getValorConserto() {
        return this.valorConserto;
    }
    
    public void setValorConserto(BigDecimal valorConserto) {
        this.valorConserto = valorConserto;
    }
    public int getPriOcorrencia() {
        return this.priOcorrencia;
    }
    
    public void setPriOcorrencia(int priOcorrencia) {
        this.priOcorrencia = priOcorrencia;
    }
    public int getEstOcorrencia() {
        return this.estOcorrencia;
    }
    
    public void setEstOcorrencia(int estOcorrencia) {
        this.estOcorrencia = estOcorrencia;
    }
    public String getObsOcorrencia() {
        return this.obsOcorrencia;
    }
    
    public void setObsOcorrencia(String obsOcorrencia) {
        this.obsOcorrencia = obsOcorrencia;
    }
    public String getProbOcorrencia() {
        return this.probOcorrencia;
    }
    
    public void setProbOcorrencia(String probOcorrencia) {
        this.probOcorrencia = probOcorrencia;
    }
    public String getDesEquipamento() {
        return this.desEquipamento;
    }
    
    public void setDesEquipamento(String desEquipamento) {
        this.desEquipamento = desEquipamento;
    }




}


