package Beans;
// Generated 03/10/2015 21:05:39 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import jcolibri.cbrcore.Attribute;

/**
 * Resultado generated by hbm2java
 */
public class Resultado implements jcolibri.cbrcore.CaseComponent {


     private int idResultado;
     private String desResultado;
     private Set casos = new HashSet(0);

    public Resultado() {
    }

    public Resultado(int idResultado) {
        this.idResultado = idResultado;
    }
    
    public Resultado(int idResultado, String desResultado, Set casos) {
       this.idResultado = idResultado;
       this.desResultado = desResultado;
       this.casos = casos;
    }
    
    @Override
    public Attribute getIdAttribute() {
        return new Attribute("idResultado", this.getClass());    
    }
   
    public int getIdResultado() {
        return this.idResultado;
    }
    
    public void setIdResultado(int idResultado) {
        this.idResultado = idResultado;
    }
    public String getDesResultado() {
        return this.desResultado;
    }
    
    public void setDesResultado(String desResultado) {
        this.desResultado = desResultado;
    }
    public Set getCasos() {
        return this.casos;
    }
    
    public void setCasos(Set casos) {
        this.casos = casos;
    }

}


