package Beans;
// Generated 03/10/2015 21:05:39 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import jcolibri.cbrcore.Attribute;

/**
 * Solucao generated by hbm2java
 */
public class Solucao implements jcolibri.cbrcore.CaseComponent {


     private int idSolucao;
     private String desSolucao;
     private Set casos = new HashSet(0);

    public Solucao() {
    }

    public Solucao(int idSolucao) {
        this.idSolucao = idSolucao;
    }
    
    public Solucao(int idSolucao, String desSolucao, Set casos) {
       this.idSolucao = idSolucao;
       this.desSolucao = desSolucao;
       this.casos = casos;
    }
    
    @Override
    public Attribute getIdAttribute() {
        return new Attribute("idSolucao", this.getClass());
    }
   
    public int getIdSolucao() {
        return this.idSolucao;
    }
    
    public void setIdSolucao(int idSolucao) {
        this.idSolucao = idSolucao;
    }
    public String getDesSolucao() {
        return this.desSolucao;
    }
    
    public void setDesSolucao(String desSolucao) {
        this.desSolucao = desSolucao;
    }
    public Set getCasos() {
        return this.casos;
    }
    
    public void setCasos(Set casos) {
        this.casos = casos;
    }




}


